import type { SampleConcept, ConceptInput } from './types';

export const sampleConcepts: SampleConcept[] = [
  {
    id: 'echo-drift',
    label: 'Echo Drift',
    description: 'Strong but risky — creatively distinctive, commercially uncertain',
    tag: 'Strong / Risky',
    input: {
      workingTitle: 'Echo Drift',
      oneSentencePitch: 'A single-player atmospheric exploration game where you navigate a dying world that remembers your choices and reshapes itself around your regrets.',
      corePlayerFantasy: 'Being the last person in a beautiful, broken world that responds to your emotional state — where exploration is melancholy, discovery is bittersweet, and the environment itself is your antagonist and companion.',
      genre: 'Atmospheric exploration / narrative adventure',
      platformTargets: 'PC (Steam), possibly console later',
      cameraControlStyle: 'Third-person, over-the-shoulder with dynamic framing that shifts based on emotional tone of the scene',
      coreGameplayLoop: 'Explore environment → discover memory fragments → make choices about what to preserve or let die → watch the world reshape around your decisions → find new paths opened by changes → repeat deeper into the world',
      keyDifferentiators: 'The world literally restructures based on player choices — not just narrative branches but physical environment changes. No combat. No HUD. The game communicates entirely through environment, sound, and subtle visual cues.',
      similarGames: 'Journey, What Remains of Edith Finch, Outer Wilds, The Unfinished Swan',
      intendedAudience: 'Adults 25-45 who appreciate art games, walking simulators with substance, and emotionally resonant experiences. The "I cried at the end of Journey" audience.',
      monetizationApproach: 'Premium purchase, $20-25 price point',
      visualStyleAmbition: 'Painterly, muted watercolor aesthetic with occasional bursts of vivid color for emotional moments. Not photorealistic — stylized and distinctive.',
      narrativeComplexity: 'High — branching environmental storytelling with multiple interpretive layers. No traditional dialogue. Story told through environment, objects, and spatial relationships.',
      technicalRiskAreas: 'Procedural world restructuring system, dynamic environmental storytelling that maintains coherence across permutations, performance optimization for large-scale environment changes in real-time',
      contentProductionBurden: 'Medium-high — each environment variant needs to feel hand-crafted even though the restructuring is systemic. Sound design is critical and needs extensive original work.',
      humanCreativeEssence: 'The emotional authenticity of the world design, the specific feeling of loss and beauty coexisting, the restraint of having no combat or traditional game systems. This needs to feel like a personal artistic statement.',
      aiToolsIntended: 'Possibly AI-assisted for initial terrain generation concepts, texture variation experiments. Core artistic direction and emotional design must be human-led.',
      developerBackground: '8 years in game dev, shipped 2 indie games (one narrative adventure, one puzzle game). Strong in Unreal Engine, moderate 3D art skills, weak in audio.',
      teamSize: '1 developer + 1 part-time sound designer',
      availableWeeklyHours: '30-35 hours',
      budgetRange: '$15,000-25,000',
      desiredTimeToPrototype: '3 months',
      desiredTimeToMVP: '12-14 months',
      nonNegotiableFeatures: 'World restructuring system, no HUD, environmental storytelling, painterly visual style',
      featuresThatCanBeCut: 'Multiple ending variations (could reduce to 2-3), dynamic weather system, photo mode',
      freePitch: '',
    },
  },
  {
    id: 'realm-forge',
    label: 'Realm Forge Online',
    description: 'Generic overscoped concept — commercially plausible on paper, creatively thin',
    tag: 'Generic / Overscoped',
    input: {
      workingTitle: 'Realm Forge Online',
      oneSentencePitch: 'A massively multiplayer open-world RPG with base building, PvP, crafting, dungeon raids, and a player-driven economy.',
      corePlayerFantasy: 'Building your own kingdom in a persistent fantasy world while competing and cooperating with thousands of other players.',
      genre: 'MMORPG / survival / sandbox',
      platformTargets: 'PC, PlayStation, Xbox, and mobile cross-play',
      cameraControlStyle: 'Third-person with optional first-person toggle',
      coreGameplayLoop: 'Gather resources → craft gear → build base → form guild → raid dungeons → PvP for territory → trade on player market → repeat at higher tier',
      keyDifferentiators: 'AI-driven NPCs that remember players, fully destructible terrain, real-time weather that affects gameplay, and a political system where players vote on server-wide rules.',
      similarGames: 'World of Warcraft, New World, Rust, Albion Online, Valheim',
      intendedAudience: 'Core gamers 16-35 who want a "forever game" they can sink thousands of hours into.',
      monetizationApproach: 'Free-to-play with battle pass, cosmetic shop, and optional subscription for premium features',
      visualStyleAmbition: 'AAA photorealistic fantasy with ray tracing, large-scale battles with 100+ players on screen',
      narrativeComplexity: 'Medium — overarching world lore with emergent player-driven stories',
      technicalRiskAreas: 'Massive multiplayer networking, server infrastructure for persistent world, cross-platform play, anti-cheat, database scalability, destructible terrain at scale',
      contentProductionBurden: 'Extreme — thousands of items, hundreds of quests, dozens of zones, continuous live-service content updates required to retain players',
      humanCreativeEssence: 'The world lore and the feeling of a living, breathing fantasy realm',
      aiToolsIntended: 'AI for NPC behavior, procedural quest generation, automated content scaling, AI-driven economy balancing',
      developerBackground: '3 years hobbyist game dev, completed a few game jam projects, some Unity experience',
      teamSize: '1 solo developer',
      availableWeeklyHours: '15-20 hours',
      budgetRange: '$5,000',
      desiredTimeToPrototype: '2 months',
      desiredTimeToMVP: '8 months',
      nonNegotiableFeatures: 'Multiplayer, open world, base building, PvP, crafting, player economy, cross-play',
      featuresThatCanBeCut: 'Maybe reduce the number of classes at launch',
      freePitch: '',
    },
  },
  {
    id: 'dead-channel',
    label: 'Dead Channel',
    description: 'Realistic solo-dev concept — tightly scoped, buildable, with a clear hook',
    tag: 'Realistic / Solo',
    input: {
      workingTitle: 'Dead Channel',
      oneSentencePitch: 'A short-form horror puzzle game where you repair a broken television that shows increasingly disturbing broadcast fragments from a world that should not exist.',
      corePlayerFantasy: 'Being alone in a dim room, fixing a mysterious TV, and slowly realizing the static is watching you back. The creeping dread of something wrong with ordinary technology.',
      genre: 'Horror / puzzle',
      platformTargets: 'PC (Steam, itch.io)',
      cameraControlStyle: 'Fixed first-person perspective, seated at a workbench',
      coreGameplayLoop: 'Receive broken TV → diagnose problem using tools → repair components (solder, replace parts, tune frequencies) → watch unsettling broadcast fragment → get next TV with escalating strangeness → repeat with increasing mechanical and narrative complexity',
      keyDifferentiators: 'Physical TV repair as core mechanic (not combat, not walking). Contained single-room setting. Horror that comes from the mundane becoming wrong. Each TV is a self-contained 15-20 minute puzzle-story.',
      similarGames: 'Iron Lung, Inscription, Papers Please, Simulacra, Pony Island',
      intendedAudience: 'Horror game fans who appreciate atmospheric dread over jump scares. Indie game enthusiasts. The "I watched someone play Iron Lung and immediately bought it" crowd. Age 20-40.',
      monetizationApproach: 'Premium purchase, $8-12 price point. Short game, priced accordingly.',
      visualStyleAmbition: 'Low-fi, CRT-aesthetic. The TV screen is the visual centerpiece with deliberately degraded broadcast footage. The room is simple but atmospheric. Not trying to be photorealistic.',
      narrativeComplexity: 'Medium — each TV broadcast tells a piece of a larger mystery. Player pieces together the story through environmental clues and broadcast content. No dialogue trees.',
      technicalRiskAreas: 'CRT shader effects, audio design for unsettling broadcast content, making physical repair mechanics feel tactile and satisfying with mouse/keyboard',
      contentProductionBurden: 'Low-medium — 8-10 TV units, each with unique puzzle mechanics and broadcast content. Contained scope. Most content is the broadcast fragments which can be mixed media.',
      humanCreativeEssence: 'The specific tone of analog horror meeting hands-on repair work. The creative writing behind each broadcast fragment. The escalating sense of wrongness. This needs a specific creative voice to feel authentic.',
      aiToolsIntended: 'Possibly AI-assisted for generating initial static/glitch texture variations. Broadcast script writing and tone must be human.',
      developerBackground: '5 years hobby game dev, shipped one small horror game on itch.io (500+ downloads), comfortable with Godot, basic 3D modeling, decent at audio editing.',
      teamSize: '1 solo developer',
      availableWeeklyHours: '20-25 hours',
      budgetRange: '$2,000-5,000',
      desiredTimeToPrototype: '6 weeks',
      desiredTimeToMVP: '4-5 months',
      nonNegotiableFeatures: 'Physical TV repair mechanic, CRT aesthetic, escalating horror tone, at least 8 unique TV puzzles',
      featuresThatCanBeCut: 'Collectible lore items in the room, alternate endings beyond the main one, achievement system',
      freePitch: '',
    },
  },
];
